(define (problem car-problem)
  (:domain car)
  (:objects)
  (:init
    (= (d) 0)
    (= (v) 0)
    (= (a) 0)
    (= (up_limit) 5)
    (= (down_limit) -5)
    (= (running_time) 0)
    (running)
    (not (engineBlown))
    (transmission_fine)
    (not (goal_reached))
  )
  (:goal
    (goal_reached)
  )
)
