(define (domain car-ma)
  (:requirements :typing :fluents :time :negative-preconditions)
  (:predicates
    (running_car1)
    (running_car2)
    (engineblown_car1)
    (engineblown_car2)
    (transmission_fine_car1)
    (transmission_fine_car2)
    (goal_reached_car1)
    (goal_reached_car2)
  )
  (:functions
    (d_car1)
    (d_car2)
    (v_car1)
    (v_car2)
    (a_car1)
    (a_car2)
    (up_limit_car1)
    (up_limit_car2)
    (down_limit_car1)
    (down_limit_car2)
    (running_time_car1)
    (running_time_car2)
  )
