(define (domain blocks)
  (:requirements :typing)
  (:predicates
    (on_block1_block2)
    (on_block1_block3)
    (on_block2_block1)
    (on_block2_block3)
    (on_block3_block1)
    (on_block3_block2)
    (ontable_block1)
    (ontable_block2)
    (ontable_block3)
    (clear_block1)
    (clear_block2)
    (clear_block3)
    (holding_agent1_block1)
    (holding_agent1_block2)
    (holding_agent1_block3)
    (holding_agent2_block1)
    (holding_agent2_block2)
    (holding_agent2_block3)
    (handempty_agent1)
    (handempty_agent2)
  )
  (:action stack_agent1_block1_block2&pick-up_agent2_block3
    :precondition (and
      (holding_agent1_block1)
      (clear_block2)
      (clear_block3)
      (ontable_block3)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block2))
      (clear_block1)
      (handempty_agent1)
      (on_block1)
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action stack_agent1_block1_block2&put-down_agent2_block3
    :precondition (and
      (holding_agent1_block1)
      (clear_block2)
      (holding_agent2_block3)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block2))
      (clear_block1)
      (handempty_agent1)
      (on_block1)
      (not (holding_agent2))
      (clear_block3)
      (handempty_agent2)
      (ontable_block3)
    )
  )
  (:action stack_agent1_block1_block3&pick-up_agent2_block2
    :precondition (and
      (holding_agent1_block1)
      (clear_block3)
      (clear_block2)
      (ontable_block2)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block3))
      (clear_block1)
      (handempty_agent1)
      (on_block1)
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action stack_agent1_block1_block3&put-down_agent2_block2
    :precondition (and
      (holding_agent1_block1)
      (clear_block3)
      (holding_agent2_block2)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block3))
      (clear_block1)
      (handempty_agent1)
      (on_block1)
      (not (holding_agent2))
      (clear_block2)
      (handempty_agent2)
      (ontable_block2)
    )
  )
  (:action stack_agent1_block2_block1&pick-up_agent2_block3
    :precondition (and
      (holding_agent1_block2)
      (clear_block1)
      (clear_block3)
      (ontable_block3)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block1))
      (clear_block2)
      (handempty_agent1)
      (on_block2)
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action stack_agent1_block2_block1&put-down_agent2_block3
    :precondition (and
      (holding_agent1_block2)
      (clear_block1)
      (holding_agent2_block3)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block1))
      (clear_block2)
      (handempty_agent1)
      (on_block2)
      (not (holding_agent2))
      (clear_block3)
      (handempty_agent2)
      (ontable_block3)
    )
  )
  (:action stack_agent1_block2_block3&pick-up_agent2_block1
    :precondition (and
      (holding_agent1_block2)
      (clear_block3)
      (clear_block1)
      (ontable_block1)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block3))
      (clear_block2)
      (handempty_agent1)
      (on_block2)
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action stack_agent1_block2_block3&put-down_agent2_block1
    :precondition (and
      (holding_agent1_block2)
      (clear_block3)
      (holding_agent2_block1)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block3))
      (clear_block2)
      (handempty_agent1)
      (on_block2)
      (not (holding_agent2))
      (clear_block1)
      (handempty_agent2)
      (ontable_block1)
    )
  )
  (:action stack_agent1_block3_block1&pick-up_agent2_block2
    :precondition (and
      (holding_agent1_block3)
      (clear_block1)
      (clear_block2)
      (ontable_block2)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block1))
      (clear_block3)
      (handempty_agent1)
      (on_block3)
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action stack_agent1_block3_block1&put-down_agent2_block2
    :precondition (and
      (holding_agent1_block3)
      (clear_block1)
      (holding_agent2_block2)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block1))
      (clear_block3)
      (handempty_agent1)
      (on_block3)
      (not (holding_agent2))
      (clear_block2)
      (handempty_agent2)
      (ontable_block2)
    )
  )
  (:action stack_agent1_block3_block2&pick-up_agent2_block1
    :precondition (and
      (holding_agent1_block3)
      (clear_block2)
      (clear_block1)
      (ontable_block1)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block2))
      (clear_block3)
      (handempty_agent1)
      (on_block3)
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action stack_agent1_block3_block2&put-down_agent2_block1
    :precondition (and
      (holding_agent1_block3)
      (clear_block2)
      (holding_agent2_block1)
    )
    :effect (and
      (not (holding_agent1))
      (not (clear_block2))
      (clear_block3)
      (handempty_agent1)
      (on_block3)
      (not (holding_agent2))
      (clear_block1)
      (handempty_agent2)
      (ontable_block1)
    )
  )
  (:action stack_agent2_block1_block2&pick-up_agent1_block3
    :precondition (and
      (holding_agent2_block1)
      (clear_block2)
      (clear_block3)
      (ontable_block3)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block2))
      (clear_block1)
      (handempty_agent2)
      (on_block1)
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent1))
      (holding_agent1)
    )
  )
  (:action stack_agent2_block1_block2&put-down_agent1_block3
    :precondition (and
      (holding_agent2_block1)
      (clear_block2)
      (holding_agent1_block3)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block2))
      (clear_block1)
      (handempty_agent2)
      (on_block1)
      (not (holding_agent1))
      (clear_block3)
      (handempty_agent1)
      (ontable_block3)
    )
  )
  (:action stack_agent2_block1_block3&pick-up_agent1_block2
    :precondition (and
      (holding_agent2_block1)
      (clear_block3)
      (clear_block2)
      (ontable_block2)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block3))
      (clear_block1)
      (handempty_agent2)
      (on_block1)
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent1))
      (holding_agent1)
    )
  )
  (:action stack_agent2_block1_block3&put-down_agent1_block2
    :precondition (and
      (holding_agent2_block1)
      (clear_block3)
      (holding_agent1_block2)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block3))
      (clear_block1)
      (handempty_agent2)
      (on_block1)
      (not (holding_agent1))
      (clear_block2)
      (handempty_agent1)
      (ontable_block2)
    )
  )
  (:action stack_agent2_block2_block1&pick-up_agent1_block3
    :precondition (and
      (holding_agent2_block2)
      (clear_block1)
      (clear_block3)
      (ontable_block3)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block1))
      (clear_block2)
      (handempty_agent2)
      (on_block2)
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent1))
      (holding_agent1)
    )
  )
  (:action stack_agent2_block2_block1&put-down_agent1_block3
    :precondition (and
      (holding_agent2_block2)
      (clear_block1)
      (holding_agent1_block3)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block1))
      (clear_block2)
      (handempty_agent2)
      (on_block2)
      (not (holding_agent1))
      (clear_block3)
      (handempty_agent1)
      (ontable_block3)
    )
  )
  (:action stack_agent2_block2_block3&pick-up_agent1_block1
    :precondition (and
      (holding_agent2_block2)
      (clear_block3)
      (clear_block1)
      (ontable_block1)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block3))
      (clear_block2)
      (handempty_agent2)
      (on_block2)
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent1))
      (holding_agent1)
    )
  )
  (:action stack_agent2_block2_block3&put-down_agent1_block1
    :precondition (and
      (holding_agent2_block2)
      (clear_block3)
      (holding_agent1_block1)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block3))
      (clear_block2)
      (handempty_agent2)
      (on_block2)
      (not (holding_agent1))
      (clear_block1)
      (handempty_agent1)
      (ontable_block1)
    )
  )
  (:action stack_agent2_block3_block1&pick-up_agent1_block2
    :precondition (and
      (holding_agent2_block3)
      (clear_block1)
      (clear_block2)
      (ontable_block2)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block1))
      (clear_block3)
      (handempty_agent2)
      (on_block3)
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent1))
      (holding_agent1)
    )
  )
  (:action stack_agent2_block3_block1&put-down_agent1_block2
    :precondition (and
      (holding_agent2_block3)
      (clear_block1)
      (holding_agent1_block2)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block1))
      (clear_block3)
      (handempty_agent2)
      (on_block3)
      (not (holding_agent1))
      (clear_block2)
      (handempty_agent1)
      (ontable_block2)
    )
  )
  (:action stack_agent2_block3_block2&pick-up_agent1_block1
    :precondition (and
      (holding_agent2_block3)
      (clear_block2)
      (clear_block1)
      (ontable_block1)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block2))
      (clear_block3)
      (handempty_agent2)
      (on_block3)
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent1))
      (holding_agent1)
    )
  )
  (:action stack_agent2_block3_block2&put-down_agent1_block1
    :precondition (and
      (holding_agent2_block3)
      (clear_block2)
      (holding_agent1_block1)
    )
    :effect (and
      (not (holding_agent2))
      (not (clear_block2))
      (clear_block3)
      (handempty_agent2)
      (on_block3)
      (not (holding_agent1))
      (clear_block1)
      (handempty_agent1)
      (ontable_block1)
    )
  )
  (:action pick-up_agent1_block1&pick-up_agent2_block2
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent1)
      (clear_block2)
      (ontable_block2)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent1))
      (holding_agent1)
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action pick-up_agent1_block1&pick-up_agent2_block3
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent1)
      (clear_block3)
      (ontable_block3)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent1))
      (holding_agent1)
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action pick-up_agent1_block1&put-down_agent2_block2
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent1)
      (holding_agent2_block2)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent1))
      (holding_agent1)
      (not (holding_agent2))
      (clear_block2)
      (handempty_agent2)
      (ontable_block2)
    )
  )
  (:action pick-up_agent1_block1&put-down_agent2_block3
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent1)
      (holding_agent2_block3)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent1))
      (holding_agent1)
      (not (holding_agent2))
      (clear_block3)
      (handempty_agent2)
      (ontable_block3)
    )
  )
  (:action pick-up_agent1_block1&unstack_agent2_block2_block3
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent1)
      (on_block2_block3)
      (clear_block2)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent1))
      (holding_agent1)
      (holding_agent2)
      (clear_block3)
      (not (clear_block2))
      (not (handempty_agent2))
      (not (on_block2))
    )
  )
  (:action pick-up_agent1_block1&unstack_agent2_block3_block2
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent1)
      (on_block3_block2)
      (clear_block3)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent1))
      (holding_agent1)
      (holding_agent2)
      (clear_block2)
      (not (clear_block3))
      (not (handempty_agent2))
      (not (on_block3))
    )
  )
  (:action pick-up_agent1_block2&pick-up_agent2_block1
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent1)
      (clear_block1)
      (ontable_block1)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent1))
      (holding_agent1)
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action pick-up_agent1_block2&pick-up_agent2_block3
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent1)
      (clear_block3)
      (ontable_block3)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent1))
      (holding_agent1)
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action pick-up_agent1_block2&put-down_agent2_block1
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent1)
      (holding_agent2_block1)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent1))
      (holding_agent1)
      (not (holding_agent2))
      (clear_block1)
      (handempty_agent2)
      (ontable_block1)
    )
  )
  (:action pick-up_agent1_block2&put-down_agent2_block3
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent1)
      (holding_agent2_block3)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent1))
      (holding_agent1)
      (not (holding_agent2))
      (clear_block3)
      (handempty_agent2)
      (ontable_block3)
    )
  )
  (:action pick-up_agent1_block2&unstack_agent2_block1_block3
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent1)
      (on_block1_block3)
      (clear_block1)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent1))
      (holding_agent1)
      (holding_agent2)
      (clear_block3)
      (not (clear_block1))
      (not (handempty_agent2))
      (not (on_block1))
    )
  )
  (:action pick-up_agent1_block2&unstack_agent2_block3_block1
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent1)
      (on_block3_block1)
      (clear_block3)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent1))
      (holding_agent1)
      (holding_agent2)
      (clear_block1)
      (not (clear_block3))
      (not (handempty_agent2))
      (not (on_block3))
    )
  )
  (:action pick-up_agent1_block3&pick-up_agent2_block1
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent1)
      (clear_block1)
      (ontable_block1)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent1))
      (holding_agent1)
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action pick-up_agent1_block3&pick-up_agent2_block2
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent1)
      (clear_block2)
      (ontable_block2)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent1))
      (holding_agent1)
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent2))
      (holding_agent2)
    )
  )
  (:action pick-up_agent1_block3&put-down_agent2_block1
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent1)
      (holding_agent2_block1)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent1))
      (holding_agent1)
      (not (holding_agent2))
      (clear_block1)
      (handempty_agent2)
      (ontable_block1)
    )
  )
  (:action pick-up_agent1_block3&put-down_agent2_block2
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent1)
      (holding_agent2_block2)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent1))
      (holding_agent1)
      (not (holding_agent2))
      (clear_block2)
      (handempty_agent2)
      (ontable_block2)
    )
  )
  (:action pick-up_agent1_block3&unstack_agent2_block1_block2
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent1)
      (on_block1_block2)
      (clear_block1)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent1))
      (holding_agent1)
      (holding_agent2)
      (clear_block2)
      (not (clear_block1))
      (not (handempty_agent2))
      (not (on_block1))
    )
  )
  (:action pick-up_agent1_block3&unstack_agent2_block2_block1
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent1)
      (on_block2_block1)
      (clear_block2)
      (handempty_agent2)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent1))
      (holding_agent1)
      (holding_agent2)
      (clear_block1)
      (not (clear_block2))
      (not (handempty_agent2))
      (not (on_block2))
    )
  )
  (:action pick-up_agent2_block1&put-down_agent1_block2
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent2)
      (holding_agent1_block2)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent2))
      (holding_agent2)
      (not (holding_agent1))
      (clear_block2)
      (handempty_agent1)
      (ontable_block2)
    )
  )
  (:action pick-up_agent2_block1&put-down_agent1_block3
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent2)
      (holding_agent1_block3)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent2))
      (holding_agent2)
      (not (holding_agent1))
      (clear_block3)
      (handempty_agent1)
      (ontable_block3)
    )
  )
  (:action pick-up_agent2_block1&unstack_agent1_block2_block3
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent2)
      (on_block2_block3)
      (clear_block2)
      (handempty_agent1)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent2))
      (holding_agent2)
      (holding_agent1)
      (clear_block3)
      (not (clear_block2))
      (not (handempty_agent1))
      (not (on_block2))
    )
  )
  (:action pick-up_agent2_block1&unstack_agent1_block3_block2
    :precondition (and
      (clear_block1)
      (ontable_block1)
      (handempty_agent2)
      (on_block3_block2)
      (clear_block3)
      (handempty_agent1)
    )
    :effect (and
      (not (ontable_block1))
      (not (clear_block1))
      (not (handempty_agent2))
      (holding_agent2)
      (holding_agent1)
      (clear_block2)
      (not (clear_block3))
      (not (handempty_agent1))
      (not (on_block3))
    )
  )
  (:action pick-up_agent2_block2&put-down_agent1_block1
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent2)
      (holding_agent1_block1)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent2))
      (holding_agent2)
      (not (holding_agent1))
      (clear_block1)
      (handempty_agent1)
      (ontable_block1)
    )
  )
  (:action pick-up_agent2_block2&put-down_agent1_block3
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent2)
      (holding_agent1_block3)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent2))
      (holding_agent2)
      (not (holding_agent1))
      (clear_block3)
      (handempty_agent1)
      (ontable_block3)
    )
  )
  (:action pick-up_agent2_block2&unstack_agent1_block1_block3
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent2)
      (on_block1_block3)
      (clear_block1)
      (handempty_agent1)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent2))
      (holding_agent2)
      (holding_agent1)
      (clear_block3)
      (not (clear_block1))
      (not (handempty_agent1))
      (not (on_block1))
    )
  )
  (:action pick-up_agent2_block2&unstack_agent1_block3_block1
    :precondition (and
      (clear_block2)
      (ontable_block2)
      (handempty_agent2)
      (on_block3_block1)
      (clear_block3)
      (handempty_agent1)
    )
    :effect (and
      (not (ontable_block2))
      (not (clear_block2))
      (not (handempty_agent2))
      (holding_agent2)
      (holding_agent1)
      (clear_block1)
      (not (clear_block3))
      (not (handempty_agent1))
      (not (on_block3))
    )
  )
  (:action pick-up_agent2_block3&put-down_agent1_block1
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent2)
      (holding_agent1_block1)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent2))
      (holding_agent2)
      (not (holding_agent1))
      (clear_block1)
      (handempty_agent1)
      (ontable_block1)
    )
  )
  (:action pick-up_agent2_block3&put-down_agent1_block2
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent2)
      (holding_agent1_block2)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent2))
      (holding_agent2)
      (not (holding_agent1))
      (clear_block2)
      (handempty_agent1)
      (ontable_block2)
    )
  )
  (:action pick-up_agent2_block3&unstack_agent1_block1_block2
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent2)
      (on_block1_block2)
      (clear_block1)
      (handempty_agent1)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent2))
      (holding_agent2)
      (holding_agent1)
      (clear_block2)
      (not (clear_block1))
      (not (handempty_agent1))
      (not (on_block1))
    )
  )
  (:action pick-up_agent2_block3&unstack_agent1_block2_block1
    :precondition (and
      (clear_block3)
      (ontable_block3)
      (handempty_agent2)
      (on_block2_block1)
      (clear_block2)
      (handempty_agent1)
    )
    :effect (and
      (not (ontable_block3))
      (not (clear_block3))
      (not (handempty_agent2))
      (holding_agent2)
      (holding_agent1)
      (clear_block1)
      (not (clear_block2))
      (not (handempty_agent1))
      (not (on_block2))
    )
  )
  (:action put-down_agent1_block1&put-down_agent2_block2
    :precondition (and
      (holding_agent1_block1)
      (holding_agent2_block2)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block1)
      (handempty_agent1)
      (ontable_block1)
      (not (holding_agent2))
      (clear_block2)
      (handempty_agent2)
      (ontable_block2)
    )
  )
  (:action put-down_agent1_block1&put-down_agent2_block3
    :precondition (and
      (holding_agent1_block1)
      (holding_agent2_block3)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block1)
      (handempty_agent1)
      (ontable_block1)
      (not (holding_agent2))
      (clear_block3)
      (handempty_agent2)
      (ontable_block3)
    )
  )
  (:action put-down_agent1_block1&unstack_agent2_block2_block3
    :precondition (and
      (holding_agent1_block1)
      (on_block2_block3)
      (clear_block2)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block1)
      (handempty_agent1)
      (ontable_block1)
      (holding_agent2)
      (clear_block3)
      (not (clear_block2))
      (not (handempty_agent2))
      (not (on_block2))
    )
  )
  (:action put-down_agent1_block1&unstack_agent2_block3_block2
    :precondition (and
      (holding_agent1_block1)
      (on_block3_block2)
      (clear_block3)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block1)
      (handempty_agent1)
      (ontable_block1)
      (holding_agent2)
      (clear_block2)
      (not (clear_block3))
      (not (handempty_agent2))
      (not (on_block3))
    )
  )
  (:action put-down_agent1_block2&put-down_agent2_block1
    :precondition (and
      (holding_agent1_block2)
      (holding_agent2_block1)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block2)
      (handempty_agent1)
      (ontable_block2)
      (not (holding_agent2))
      (clear_block1)
      (handempty_agent2)
      (ontable_block1)
    )
  )
  (:action put-down_agent1_block2&put-down_agent2_block3
    :precondition (and
      (holding_agent1_block2)
      (holding_agent2_block3)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block2)
      (handempty_agent1)
      (ontable_block2)
      (not (holding_agent2))
      (clear_block3)
      (handempty_agent2)
      (ontable_block3)
    )
  )
  (:action put-down_agent1_block2&unstack_agent2_block1_block3
    :precondition (and
      (holding_agent1_block2)
      (on_block1_block3)
      (clear_block1)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block2)
      (handempty_agent1)
      (ontable_block2)
      (holding_agent2)
      (clear_block3)
      (not (clear_block1))
      (not (handempty_agent2))
      (not (on_block1))
    )
  )
  (:action put-down_agent1_block2&unstack_agent2_block3_block1
    :precondition (and
      (holding_agent1_block2)
      (on_block3_block1)
      (clear_block3)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block2)
      (handempty_agent1)
      (ontable_block2)
      (holding_agent2)
      (clear_block1)
      (not (clear_block3))
      (not (handempty_agent2))
      (not (on_block3))
    )
  )
  (:action put-down_agent1_block3&put-down_agent2_block1
    :precondition (and
      (holding_agent1_block3)
      (holding_agent2_block1)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block3)
      (handempty_agent1)
      (ontable_block3)
      (not (holding_agent2))
      (clear_block1)
      (handempty_agent2)
      (ontable_block1)
    )
  )
  (:action put-down_agent1_block3&put-down_agent2_block2
    :precondition (and
      (holding_agent1_block3)
      (holding_agent2_block2)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block3)
      (handempty_agent1)
      (ontable_block3)
      (not (holding_agent2))
      (clear_block2)
      (handempty_agent2)
      (ontable_block2)
    )
  )
  (:action put-down_agent1_block3&unstack_agent2_block1_block2
    :precondition (and
      (holding_agent1_block3)
      (on_block1_block2)
      (clear_block1)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block3)
      (handempty_agent1)
      (ontable_block3)
      (holding_agent2)
      (clear_block2)
      (not (clear_block1))
      (not (handempty_agent2))
      (not (on_block1))
    )
  )
  (:action put-down_agent1_block3&unstack_agent2_block2_block1
    :precondition (and
      (holding_agent1_block3)
      (on_block2_block1)
      (clear_block2)
      (handempty_agent2)
    )
    :effect (and
      (not (holding_agent1))
      (clear_block3)
      (handempty_agent1)
      (ontable_block3)
      (holding_agent2)
      (clear_block1)
      (not (clear_block2))
      (not (handempty_agent2))
      (not (on_block2))
    )
  )
  (:action put-down_agent2_block1&unstack_agent1_block2_block3
    :precondition (and
      (holding_agent2_block1)
      (on_block2_block3)
      (clear_block2)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (clear_block1)
      (handempty_agent2)
      (ontable_block1)
      (holding_agent1)
      (clear_block3)
      (not (clear_block2))
      (not (handempty_agent1))
      (not (on_block2))
    )
  )
  (:action put-down_agent2_block1&unstack_agent1_block3_block2
    :precondition (and
      (holding_agent2_block1)
      (on_block3_block2)
      (clear_block3)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (clear_block1)
      (handempty_agent2)
      (ontable_block1)
      (holding_agent1)
      (clear_block2)
      (not (clear_block3))
      (not (handempty_agent1))
      (not (on_block3))
    )
  )
  (:action put-down_agent2_block2&unstack_agent1_block1_block3
    :precondition (and
      (holding_agent2_block2)
      (on_block1_block3)
      (clear_block1)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (clear_block2)
      (handempty_agent2)
      (ontable_block2)
      (holding_agent1)
      (clear_block3)
      (not (clear_block1))
      (not (handempty_agent1))
      (not (on_block1))
    )
  )
  (:action put-down_agent2_block2&unstack_agent1_block3_block1
    :precondition (and
      (holding_agent2_block2)
      (on_block3_block1)
      (clear_block3)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (clear_block2)
      (handempty_agent2)
      (ontable_block2)
      (holding_agent1)
      (clear_block1)
      (not (clear_block3))
      (not (handempty_agent1))
      (not (on_block3))
    )
  )
  (:action put-down_agent2_block3&unstack_agent1_block1_block2
    :precondition (and
      (holding_agent2_block3)
      (on_block1_block2)
      (clear_block1)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (clear_block3)
      (handempty_agent2)
      (ontable_block3)
      (holding_agent1)
      (clear_block2)
      (not (clear_block1))
      (not (handempty_agent1))
      (not (on_block1))
    )
  )
  (:action put-down_agent2_block3&unstack_agent1_block2_block1
    :precondition (and
      (holding_agent2_block3)
      (on_block2_block1)
      (clear_block2)
      (handempty_agent1)
    )
    :effect (and
      (not (holding_agent2))
      (clear_block3)
      (handempty_agent2)
      (ontable_block3)
      (holding_agent1)
      (clear_block1)
      (not (clear_block2))
      (not (handempty_agent1))
      (not (on_block2))
    )
  )
)
