(define (problem roverprob1425) (:domain rover)
(:objects
	objective2 - objective
	waypoint8 - waypoint
	waypoint9 - waypoint
	waypoint6 - waypoint
	rover3store - store
	waypoint4 - waypoint
	waypoint5 - waypoint
	rover0store - store
	waypoint2 - waypoint
	waypoint0 - waypoint
	general - lander
	objective3 - objective
	waypoint1 - waypoint
	objective0 - objective
	colour - mode
	waypoint3 - waypoint
	objective1 - objective
	camera1 - camera
	camera2 - camera
	camera3 - camera
	camera4 - camera
	rover2store - store
	waypoint7 - waypoint
	rover1store - store
	low_res - mode
	rover3 - rover
	camera0 - camera
	rover2 - rover
	rover1 - rover
	rover0 - rover
)

(:init
	(on_board camera3 rover1)
	(can_traverse rover1 waypoint6 waypoint8)
	(equipped_for_imaging rover1)
	(can_traverse rover0 waypoint5 waypoint4)
	(can_traverse rover0 waypoint8 waypoint1)
	(available rover1)
	(visible waypoint2 waypoint1)
	(supports camera3 low_res)
	(visible waypoint4 waypoint1)
	(calibration_target camera0 objective2)
	(equipped_for_soil_analysis rover0)
	(on_board camera4 rover0)
	(calibration_target camera2 objective3)
	(at_soil_sample waypoint3)
	(equipped_for_imaging rover3)
	(visible waypoint4 waypoint0)
	(visible waypoint4 waypoint6)
	(visible waypoint8 waypoint7)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint5 waypoint4)
	(visible waypoint6 waypoint3)
	(visible_from objective2 waypoint7)
	(visible waypoint7 waypoint5)
	(visible_from objective3 waypoint3)
	(can_traverse rover2 waypoint4 waypoint0)
	(can_traverse rover1 waypoint7 waypoint5)
	(can_traverse rover1 waypoint4 waypoint5)
	(at_soil_sample waypoint9)
	(can_traverse rover3 waypoint8 waypoint6)
	(visible waypoint7 waypoint1)
	(can_traverse rover2 waypoint6 waypoint0)
	(can_traverse rover3 waypoint9 waypoint2)
	(can_traverse rover1 waypoint0 waypoint3)
	(on_board camera0 rover3)
	(available rover2)
	(visible waypoint6 waypoint4)
	(can_traverse rover0 waypoint8 waypoint7)
	(visible waypoint4 waypoint2)
	(visible_from objective0 waypoint5)
	(visible_from objective3 waypoint1)
	(visible waypoint3 waypoint6)
	(visible waypoint7 waypoint8)
	(visible waypoint6 waypoint2)
	(can_traverse rover3 waypoint1 waypoint2)
	(visible_from objective0 waypoint4)
	(can_traverse rover3 waypoint7 waypoint1)
	(store_of rover2store rover2)
	(supports camera1 colour)
	(visible_from objective3 waypoint4)
	(visible waypoint1 waypoint4)
	(equipped_for_imaging rover0)
	(visible waypoint6 waypoint1)
	(visible_from objective1 waypoint2)
	(can_traverse rover2 waypoint4 waypoint5)
	(visible_from objective1 waypoint3)
	(visible waypoint3 waypoint9)
	(can_traverse rover0 waypoint0 waypoint4)
	(available rover3)
	(calibration_target camera3 objective0)
	(visible waypoint4 waypoint8)
	(can_traverse rover3 waypoint1 waypoint5)
	(visible_from objective0 waypoint0)
	(visible waypoint6 waypoint5)
	(can_traverse rover2 waypoint4 waypoint8)
	(at rover2 waypoint0)
	(visible waypoint8 waypoint4)
	(visible waypoint0 waypoint4)
	(can_traverse rover1 waypoint2 waypoint4)
	(can_traverse rover2 waypoint4 waypoint1)
	(can_traverse rover1 waypoint4 waypoint0)
	(at_lander general waypoint7)
	(visible waypoint4 waypoint9)
	(visible waypoint1 waypoint7)
	(can_traverse rover2 waypoint3 waypoint2)
	(visible_from objective1 waypoint5)
	(can_traverse rover0 waypoint4 waypoint5)
	(visible waypoint2 waypoint4)
	(can_traverse rover2 waypoint8 waypoint4)
	(visible waypoint2 waypoint6)
	(visible_from objective0 waypoint2)
	(can_traverse rover3 waypoint1 waypoint4)
	(can_traverse rover1 waypoint8 waypoint6)
	(visible waypoint9 waypoint6)
	(can_traverse rover3 waypoint2 waypoint1)
	(can_traverse rover1 waypoint6 waypoint4)
	(visible waypoint5 waypoint4)
	(at rover3 waypoint2)
	(can_traverse rover3 waypoint6 waypoint0)
	(visible_from objective3 waypoint6)
	(can_traverse rover3 waypoint1 waypoint7)
	(store_of rover0store rover0)
	(can_traverse rover2 waypoint1 waypoint4)
	(can_traverse rover2 waypoint0 waypoint3)
	(can_traverse rover2 waypoint9 waypoint0)
	(visible waypoint6 waypoint9)
	(can_traverse rover1 waypoint5 waypoint7)
	(visible waypoint2 waypoint5)
	(can_traverse rover3 waypoint6 waypoint8)
	(on_board camera1 rover2)
	(at_rock_sample waypoint4)
	(can_traverse rover0 waypoint3 waypoint2)
	(can_traverse rover3 waypoint2 waypoint9)
	(visible_from objective3 waypoint5)
	(visible waypoint5 waypoint1)
	(supports camera0 colour)
	(visible waypoint5 waypoint7)
	(can_traverse rover3 waypoint3 waypoint6)
	(visible waypoint5 waypoint3)
	(can_traverse rover0 waypoint4 waypoint1)
	(visible waypoint0 waypoint3)
	(equipped_for_soil_analysis rover1)
	(empty rover1store)
	(store_of rover3store rover3)
	(can_traverse rover2 waypoint0 waypoint9)
	(visible_from objective0 waypoint3)
	(visible waypoint9 waypoint0)
	(visible waypoint2 waypoint9)
	(visible waypoint0 waypoint9)
	(visible_from objective1 waypoint6)
	(can_traverse rover1 waypoint1 waypoint2)
	(can_traverse rover1 waypoint4 waypoint6)
	(at rover0 waypoint1)
	(can_traverse rover1 waypoint9 waypoint4)
	(can_traverse rover1 waypoint5 waypoint4)
	(can_traverse rover1 waypoint4 waypoint9)
	(can_traverse rover0 waypoint1 waypoint4)
	(channel_free general)
	(visible_from objective1 waypoint0)
	(visible waypoint9 waypoint3)
	(can_traverse rover0 waypoint1 waypoint2)
	(visible waypoint3 waypoint0)
	(visible_from objective2 waypoint1)
	(at rover1 waypoint4)
	(supports camera4 low_res)
	(visible waypoint3 waypoint2)
	(visible waypoint9 waypoint2)
	(empty rover3store)
	(visible_from objective2 waypoint8)
	(visible waypoint9 waypoint4)
	(visible_from objective2 waypoint2)
	(supports camera4 colour)
	(can_traverse rover1 waypoint3 waypoint0)
	(at_soil_sample waypoint4)
	(can_traverse rover3 waypoint5 waypoint1)
	(available rover0)
	(equipped_for_rock_analysis rover1)
	(can_traverse rover1 waypoint4 waypoint2)
	(at_rock_sample waypoint8)
	(can_traverse rover0 waypoint7 waypoint8)
	(empty rover2store)
	(visible waypoint1 waypoint6)
	(visible waypoint1 waypoint5)
	(visible waypoint8 waypoint9)
	(visible waypoint6 waypoint0)
	(visible waypoint1 waypoint8)
	(visible_from objective2 waypoint6)
	(can_traverse rover0 waypoint1 waypoint8)
	(supports camera3 colour)
	(visible_from objective0 waypoint1)
	(visible_from objective2 waypoint5)
	(can_traverse rover3 waypoint4 waypoint1)
	(can_traverse rover0 waypoint4 waypoint9)
	(visible_from objective2 waypoint3)
	(calibration_target camera4 objective3)
	(can_traverse rover0 waypoint1 waypoint6)
	(can_traverse rover2 waypoint3 waypoint0)
	(can_traverse rover2 waypoint0 waypoint4)
	(visible waypoint5 waypoint6)
	(can_traverse rover2 waypoint2 waypoint3)
	(visible waypoint3 waypoint7)
	(at_rock_sample waypoint3)
	(can_traverse rover0 waypoint9 waypoint4)
	(visible_from objective3 waypoint2)
	(can_traverse rover2 waypoint0 waypoint6)
	(visible_from objective2 waypoint4)
	(can_traverse rover3 waypoint2 waypoint6)
	(visible waypoint8 waypoint1)
	(visible waypoint8 waypoint6)
	(visible waypoint5 waypoint2)
	(visible_from objective2 waypoint0)
	(can_traverse rover0 waypoint2 waypoint3)
	(at_rock_sample waypoint1)
	(store_of rover1store rover1)
	(can_traverse rover3 waypoint6 waypoint2)
	(visible waypoint4 waypoint5)
	(visible waypoint3 waypoint5)
	(visible waypoint2 waypoint3)
	(visible_from objective3 waypoint0)
	(at_rock_sample waypoint5)
	(visible waypoint9 waypoint8)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint4)
	(visible waypoint0 waypoint6)
	(visible waypoint6 waypoint8)
	(can_traverse rover1 waypoint2 waypoint1)
	(empty rover0store)
	(can_traverse rover1 waypoint0 waypoint4)
	(supports camera2 low_res)
	(calibration_target camera1 objective3)
	(visible waypoint1 waypoint2)
	(can_traverse rover0 waypoint6 waypoint1)
	(at_soil_sample waypoint6)
	(can_traverse rover0 waypoint4 waypoint0)
	(supports camera0 low_res)
	(visible_from objective0 waypoint6)
	(on_board camera2 rover1)
	(can_traverse rover3 waypoint6 waypoint3)
	(can_traverse rover3 waypoint0 waypoint6)
	(visible waypoint7 waypoint3)
	(can_traverse rover0 waypoint2 waypoint1)
)

(:goal
	(and
	(communicated_rock_data waypoint5)
	(communicated_image_data objective2 low_res)
	(communicated_rock_data waypoint8)
	(communicated_soil_data waypoint6)
	(communicated_image_data objective0 colour)
	(communicated_soil_data waypoint3)
	(communicated_rock_data waypoint4)
	(communicated_image_data objective0 low_res)	
)
)

)